# Generated by Django 5.2.11 on 2026-02-22 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='outro_campo',
            field=models.BooleanField(default=False),
        ),
    ]
